### ISSUE TITLE
[Bug] CompatibleListenerTypes not set when creating Grunt Template

### ISSUE THREAD

**Issue by mpgn** [cobbr/Covenant#158]
**Bug**

The field "CompatibleListenerTypes" is not set even if we select "HTTP" or "SMB". After we click Edit, we go back on the Template, the *CompatibleListenerTypes* is set to "Nothing Selected"

It's defeating the purpose of template since we cannot select the custom template on the Launchers ...

**To Reproduce**
1. Go to Templates
2. Click on Creates
3. Set *CompatibleListenerTypes* to HTTP
4. Click "Edit"
5. Go back on the custom template and *CompatibleListenerTypes* is set to "Nothing Selected

**Expected behavior**
*CompatibleListenerTypes* should be set to HTTP or SMB

**Screenshots**

![image](https://user-images.githubusercontent.com/5891788/76870264-c689dd00-6869-11ea-8550-87a76508ff64.png)

**Covenant Server Information:**
 - OS: Windows 10

**Browser Information:**
 - Browser Chrome latest version

**Comment by cobbr** [comment]
@mpgn I think this should be fixed in the new version 79c45e7

Can you verify this problem is fixed for you?

**Comment by cobbr** [comment]
Closing for now, feel free to reopen if you continue to have problems.

**Comment by paulsg** [comment]
The same bug still exists when calling the API directly. 

POST or PUT to /api/implanttemplates

{"id": "5", "name": "CustomAgent", "description": "Custom Worker", "language": "CSharp", "commType": "HTTP", "implantDirection": "Pull", "compatibleListenerTypes": [{"id": 1, "name": "HTTP", "description": "Listens on HTTP protocol."}, {"id": 2, "name": "Bridge", "description": "Creates a C2 Bridge for custom listeners."}], "compatibleDotNetVersions": ["net35", "net40"], "stagerCode": "customcode, "executorCode": "customcode"}

Only ever returns ,"compatibleListenerTypes":[] 

Only way I have found to apply this setting is manually via the UI

**Comment by cobbr** [comment]
@paulsg Can you try again on the dev branch? I think this should be fixed now.

**Comment by cobbr** [comment]
Closing for now, can reopen if you continue to have problems.
